### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by vay1314** [azurstar/MIUIhelper#1]
在部署项目后，运行时提示以下错误，感觉好像是元素点击问题？
`Traceback (most recent call last):
  File "main.py", line 14, in <module>
    Answer(account=Account["account"], password=Account["password"])
  File "/www/MIUIhelper/web.py", line 34, in Answer
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.LINK_TEXT, "密码登录"))).click()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by azurstar** [comment]
应该是点击的问题，你可以尝试在`web.py`里调整一下时间，应该是我设置的时间太短，这个元素还没有出来就超时了...

**Comment by vay1314** [comment]
> 应该是点击的，你可以试一下在`web.py`里一下时间，应该是我设置的时间太短了，这个元素还没有出来就解决问题了……
调整wait_time 为 30，还是这个报错。我测试win下正常，但我在linux下运行不了

**Comment by azurstar** [comment]
我的CentOS 7是可以正常运行的，你可以先检查一下浏览器和driver版本号是否对应，也可以试试桌面打开浏览器看看页面需要加载多久

**Comment by vay1314** [comment]
> 我的CentOS 7是可以正常运行的，你可以先检查一下浏览器和driver版本号是否对应，也可以试试桌面打开浏览器看看页面需要加载多久 目前我也只发现了这两个原因会超时(感觉linux下加载网页比win久了很多...)

我也是centos7，好像是linux加载的时间长，不清楚为啥By.NAME、By.LINK_TEXT这些会造成超时。我刚把web中的By定位方式都改成了By.XPATH，然后在linux下测试就全部成功了

**Comment by vay1314** [comment]
By.XPATH方法
`WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/div[4]/div[2]/a'))).click()
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/div[1]/div[2]/div/div[1]/div/div/input'))).send_keys(account)
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div[1]/div/input'))).send_keys(password)
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/div[3]/label/span[1]'))).click()
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/button'))).click()`

**Comment by azurstar** [comment]
谢谢老哥的分享，明天就把这些地方改了

**Comment by forggy0113** [comment]
我用的是 Manjaro 用了新的 `By.XPATH` 版本 還是無法運行
`wait_time` 改成30也沒有辦法

**Comment by vay1314** [comment]
> 我用的是 Manjaro 用了新的`By.XPATH`版本还是无法运行 `wait_time`改成 30 也没有办法

你试试作者之前的By.NAME、By.LINK_TEXT等方法呢？最好看看无法运行的报错信息

**Comment by azurstar** [comment]
> 我用的是 Manjaro 用了新的 `By.XPATH` 版本 還是無法運行 `wait_time` 改成30也沒有辦法

可以尝试一下在web文件中把--headless那行注释掉，看看浏览器卡在了哪里了

**Comment by forggy0113** [comment]
我有註解掉 但是程序沒跑出chrome gui 視窗

**Comment by forggy0113** [comment]
請問有archive嗎 我找不到legacy檔案

**Comment by azurstar** [comment]
> 我有註解掉 但是程序沒跑出chrome gui 視窗

有报错的话 麻烦发一下
如果是卡住的话 可以考虑更换一下driver(比如firefox用[geckodriver](https://github.com/mozilla/geckodriver))
(最近才知道selenium 我对这个还不太了解...)

> 請問有archive嗎 我找不到legacy檔案

没有欸

**Comment by forggy0113** [comment]
用chrome時
`
Traceback (most recent call last):
  File "/home/zheng/MIUIhelper-main/main.py", line 14, in <module>
    answer = Answer(account=Account["account"], password=Account["password"])
  File "/home/zheng/MIUIhelper-main/web.py", line 36, in Answer
    WebDriverWait(MIUI, wait_time).until(EC.visibility_of_element_located((By.XPATH, "//*[@id='root']/div/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[1]/form/div[1]/div[4]/div[2]/a"))).click()  # 点击密码登录
  File "/home/zheng/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55bfe32207d3 <unknown>
#1 0x55bfe2f7c688 <unknown>
#2 0x55bfe2fb2c21 <unknown>
#3 0x55bfe2fb2de1 <unknown>
#4 0x55bfe2fe5d74 <unknown>
#5 0x55bfe2fd06dd <unknown>
#6 0x55bfe2fe3a0c <unknown>
#7 0x55bfe2fd05a3 <unknown>
#8 0x55bfe2fa5ddc <unknown>
#9 0x55bfe2fa6de5 <unknown>
#10 0x55bfe325149d <unknown>
#11 0x55bfe326a60c <unknown>
#12 0x55bfe3253205 <unknown>
#13 0x55bfe326aee5 <unknown>
#14 0x55bfe3247070 <unknown>
#15 0x55bfe3286488 <unknown>
#16 0x55bfe328660c <unknown>
#17 0x55bfe329fc6d <unknown>
#18 0x7ff2e5c855c2 <unknown>
`

**Comment by forggy0113** [comment]
現在的狀態是卡在登入時輸入帳號的時候

**Comment by azurstar** [comment]
> 現在的狀態是卡在登入時輸入帳號的時候

我想到一种可能，应该是中国与海外的XPATH不一致导致的，我挂梯子上网的时候，就有过类似情况

**Comment by forggy0113** [comment]
我嘗試改改看海外XPATH看看好了

**Comment by forggy0113** [comment]
改了XPATH之後就完美運作了

**Comment by forggy0113** [comment]
請問有題目庫為何還會產生随机选择的狀況
`
已进入答题页面！
准备开始答题...
尝试次数: 1
 在需要尽可能保留数据的情况下，线刷的刷机流程应该是?--先备份数据，解锁BL再刷机
尝试次数: 2
 小米在哪个城市成立？--北京
尝试次数: 3
 线刷需要手机进入什么模式？--FastBoot
尝试次数: 4
 下面哪些是MIUI13的特色功能--以上都是
尝试次数: 5
 下面哪些是MIUI13的特色功能--小米妙享中心--无法判断,已随机选择!
尝试次数: 6
 下列选项中，哪个是正确的--橙色星期五
尝试次数: 8
正在收集题目数据...
数据收集完成！
开始尝试寻找其他账号...
`

**Comment by azurstar** [comment]
> 請問有題目庫為何還會產生随机选择的狀況

你可以看一下账号是否拿到分了，第一个`下面哪些是MIUI13的特色功能--以上都是`这步应该已经完成了回答，但由于未知原因第二次出现了这个题目  
初步推测是因为题目没及时刷新导致的，晚些我拿其他账号试试
