### ISSUE TITLE
signature参数搞定，换用requests可以提上日程了

### ISSUE THREAD

**Issue by azurstar** [azurstar/MIUIhelper#3]
![signature](https://user-images.githubusercontent.com/91844313/160963545-39185bdd-bd16-412b-b18f-f9af16c1f310.png)
不过我内测分已经够了，慢慢写了，如果有人能一起弄就更好了...

**Comment by zzwk** [comment]
好强！求问大佬是从网页的js里慢慢推出来算法的吗。。

**Comment by azurstar** [comment]
不是，我就突然想到不如翻翻js看看会不会有收获，就发现了一个很像的东西，然后弄了一下就发现signature对上了...
